# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resyndeo < Formula
  desc "macOS installer for Syndeo's local k3d cluster."
  homepage "https://resyndeo.com"
  version "0.30.1"
  license "proprietary"

  depends_on "helm"
  depends_on "k3d"

  on_macos do
    if Hardware::CPU.intel?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.30.1/resyndeo_darwin_amd64.tar.gz"
      sha256 "d74a428c6bf8b24d2caf23259abaa4cd9212bdc1d0f8332ba718ad16519201f4"

      define_method(:install) do
        bin.install "resyndeo"
      end
    end
    if Hardware::CPU.arm?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.30.1/resyndeo_darwin_arm64.tar.gz"
      sha256 "2fc3ec041a3bdd604e4eb19e19e5475e03c3ce98a647bbe1a928a23b989cee9a"

      define_method(:install) do
        bin.install "resyndeo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.30.1/resyndeo_linux_amd64.tar.gz"
      sha256 "a7d5c237b90dbe6ac8d42e645c5ce12bf3ee31cde9089a63fbf21355f909473d"
      define_method(:install) do
        bin.install "resyndeo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.30.1/resyndeo_linux_arm64.tar.gz"
      sha256 "a3b53cbcc8a783a23261542feb3b61445e384b0e5a82f1f359d07d9afb526278"
      define_method(:install) do
        bin.install "resyndeo"
      end
    end
  end
end
