# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resyndeo < Formula
  desc "macOS installer for Syndeo's local k3d cluster."
  homepage "https://resyndeo.com"
  version "0.32.1"
  license "proprietary"

  depends_on "helm"
  depends_on "k3d"

  on_macos do
    if Hardware::CPU.intel?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.32.1/resyndeo_darwin_amd64.tar.gz"
      sha256 "160c617ae534b466f712f6cb3998ded26ba4e178bb45ba929585457c27587987"

      define_method(:install) do
        bin.install "resyndeo"
      end
    end
    if Hardware::CPU.arm?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.32.1/resyndeo_darwin_arm64.tar.gz"
      sha256 "c97b798da5681dea02ea9a6cc0c8eb4b8d3ff8252b19357682f620bfa4e991b0"

      define_method(:install) do
        bin.install "resyndeo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.32.1/resyndeo_linux_amd64.tar.gz"
      sha256 "bb2062b6f6f6d864a590e260c1af795b4ce1cdfd432b8a1fb921a2a5352da5f9"
      define_method(:install) do
        bin.install "resyndeo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://syndeo-releases-dev.s3.us-east-1.amazonaws.com/resyndeo/v0.32.1/resyndeo_linux_arm64.tar.gz"
      sha256 "8b0a54839d583a0cc8ce59fa4342fa35ddc92acd56c47ace9c97c740ffe26b01"
      define_method(:install) do
        bin.install "resyndeo"
      end
    end
  end
end
